#app.yaml
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  script: main.app

- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
